version: '3.8'

services:
  app:
    image: ghcr.io/rjunioramorim/boxeapp:latest
    networks:
      - network_public
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CRON_SECRET=${CRON_SECRET}
      - TZ=America/Sao_Paulo
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app.rule=Host(`smarttcode.com.br`)"
        - "traefik.http.routers.app.entrypoints=websecure"
        - "traefik.http.routers.app.tls.certresolver=letsencrypt"
        - "traefik.http.services.app.loadbalancer.server.port=3000"
        - "traefik.docker.network=network_public"

networks:
  network_public:
    name: network_public
    external: true
  